# Generated by Django 6.0.3 on 2026-03-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('страна', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200)),
                ('описание', models.TextField()),
                ('фото_товара', models.ImageField(upload_to='products/')),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10)),
                ('количество_на_складе', models.IntegerField()),
                ('категория', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category')),
                ('производитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField()),
                ('корзина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.basket')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
            ],
        ),
    ]
