# Generated by Django 6.0.6 on 2026-06-17 00:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('адрес_доставки', models.CharField(max_length=300)),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('общая_стоимость', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название_товара', models.CharField(max_length=200)),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10)),
                ('количество', models.PositiveIntegerField()),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='позиции', to='shopapp.order')),
                ('товар', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.product')),
            ],
        ),
    ]
