# Generated by Django 6.0.6 on 2026-06-17 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('роль', models.CharField(choices=[('CUSTOMER', 'Покупатель'), ('MANAGER', 'Менеджер'), ('ADMIN', 'Администратор')], default='CUSTOMER', max_length=20)),
                ('полное_имя', models.CharField(blank=True, max_length=150)),
                ('телефон', models.CharField(blank=True, max_length=20)),
                ('город_доставки', models.CharField(blank=True, max_length=100)),
                ('любимая_категория', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.category')),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
